# Site settings
title: FelixHuang
email: huangfenghua_47@163.com
description: "www change everything!"
baseurl: "/Blog"
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
